package traincraft.development.gametest;

import net.minecraft.core.BlockPos;
import net.minecraft.core.Holder;
import net.minecraft.gametest.framework.GameTestHelper;
import net.minecraft.gametest.framework.TestData;
import net.minecraft.gametest.framework.TestEnvironmentDefinition;
import net.minecraft.resources.Identifier;
import net.minecraft.world.entity.player.Player;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.Items;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.block.Rotation;
import net.minecraft.world.phys.Vec3;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.neoforge.event.RegisterGameTestsEvent;

import traincraft.Traincraft;
import traincraft.bootstrap.BlockRegistry;
import traincraft.bootstrap.EntityRegistry;
import traincraft.track.Placement;
import traincraft.track.TrackMovement;
import traincraft.track.TrackPlacementPlanner;
import traincraft.track.TrackPlacer;
import traincraft.track.TrackPlan;
import traincraft.track.TrackPlanCatalog;
import traincraft.track.TrackType;
import traincraft.track.block.TrackBlock;
import traincraft.track.block.TrackBlockEntity;
import traincraft.track.block.TrackOccupancyBlock;
import traincraft.vehicle.coupling.LinkHandler;
import traincraft.vehicle.coupling.VehicleEnd;
import traincraft.vehicle.entity.AliceLocomotiveEntity;
import traincraft.vehicle.entity.FreightCartYellowEntity;
import traincraft.vehicle.entity.LocomotiveEntity;
import traincraft.vehicle.entity.SteamLocomotiveEntity;
import traincraft.vehicle.simulation.HeatState;

import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.Consumer;

/**
 * The game tests, and the argument for which ones exist.
 *
 * <p>The unit tests already check the placement table against the golden fixtures, box for box,
 * without a server. What they cannot check is whether the same table, run through a real {@code
 * Level}, writes the blocks it describes -- registries, block states, block entities and neighbour
 * updates all sit between the plan and the world. That is what these are for, and it is why there
 * are four of them rather than one per track type: a fifth copy of "the table matches the fixture"
 * proves nothing the first one did not.
 *
 * <p>26.2 wants a registered instance and a structure template per test rather than an annotated
 * method; {@link ScenarioTestInstance} carries the name and this class holds the bodies.
 */
@EventBusSubscriber(modid = traincraft.development.DevelopmentMod.MODID)
public final class RailwayGameTests {

    /** The empty template every test starts from, generated by {@code gradlew tc structure}. */
    private static final Identifier STRUCTURE =
            Identifier.fromNamespaceAndPath(Traincraft.MODID, "empty");

    private RailwayGameTests() {}

    @SubscribeEvent
    static void register(RegisterGameTestsEvent event) {
        Holder<TestEnvironmentDefinition<?>> environment =
                event.registerEnvironment(
                        Identifier.fromNamespaceAndPath(Traincraft.MODID, "default"),
                        new TestEnvironmentDefinition.AllOf(java.util.List.of()));

        for (String name : bodies().keySet()) {
            TestData<Holder<TestEnvironmentDefinition<?>>> data =
                    new TestData<>(
                            environment,
                            STRUCTURE,
                            400,
                            0,
                            true,
                            Rotation.NONE,
                            false,
                            1,
                            1,
                            true,
                            1);
            event.registerTest(
                    Identifier.fromNamespaceAndPath(Traincraft.MODID, name),
                    new ScenarioTestInstance(name, data));
        }
    }

    /** Name to body. The registration above walks this, so adding a test is adding an entry. */
    static Map<String, Consumer<GameTestHelper>> bodies() {
        Map<String, Consumer<GameTestHelper>> bodies = new LinkedHashMap<>();
        CollisionGameTests.register(bodies);
        ElectricGameTests.register(bodies);
        DieselGameTests.register(bodies);
        AssemblyGameTests.register(bodies);
        CarGameTests.register(bodies);
        RecipeGameTests.register(bodies);
        VillageGameTests.register(bodies);
        LockGameTests.register(bodies);
        ZeppelinGameTests.register(bodies);
        bodies.put("every_track_type_places", RailwayGameTests::everyTrackTypePlaces);
        bodies.put("breaking_one_block_takes_the_piece", RailwayGameTests::breakingTakesThePiece);
        bodies.put(
                "breaking_track_preserves_adjacent_piece",
                RailwayGameTests::preservesAdjacentPiece);
        bodies.put(
                "blocked_placement_changes_nothing",
                RailwayGameTests::blockedPlacementChangesNothing);
        bodies.put(
                "thrown_switch_rewrites_the_route", RailwayGameTests::thrownSwitchRewritesTheRoute);
        bodies.put("chme3_crosses_parallel_switch", RailwayGameTests::chme3CrossesParallelSwitch);
        bodies.put(
                "trailing_through_a_thrown_switch_runs_straight",
                RailwayGameTests::trailingThroughThrownSwitch);
        bodies.put("locomotive_burns_fuel", RailwayGameTests::locomotiveBurnsFuel);
        bodies.put("locomotive_aligns_with_track", RailwayGameTests::locomotiveAlignsWithTrack);
        bodies.put("stock_is_aligned_when_placed", RailwayGameTests::stockIsAlignedWhenPlaced);
        bodies.put("cold_locomotive_will_not_move", RailwayGameTests::coldLocomotiveWillNotMove);
        bodies.put("coupleable_stock_couples", RailwayGameTests::coupleableStockCouples);
        bodies.put("a_stretched_coupling_pulls", RailwayGameTests::aStretchedCouplingPulls);
        bodies.put("a_lost_link_is_dropped", RailwayGameTests::aLostLinkIsDropped);
        bodies.put("parallel_track_does_not_couple", RailwayGameTests::parallelTrackDoesNotCouple);
        bodies.put(
                "coupled_stock_does_not_couple_twice",
                RailwayGameTests::coupledStockDoesNotCoupleTwice);
        bodies.put(
                "decoupling_a_middle_car_splits_the_consist",
                RailwayGameTests::decouplingAMiddleCarSplits);
        bodies.put("freight_keeps_its_cargo", RailwayGameTests::freightKeepsItsCargo);
        bodies.put("track_refuses_to_float", RailwayGameTests::trackRefusesToFloat);
        bodies.put("track_dies_when_its_support_goes", RailwayGameTests::trackDiesWithItsSupport);
        bodies.put("a_rail_is_not_ground_for_a_rail", RailwayGameTests::aRailIsNotGroundForARail);
        bodies.put("a_small_straight_follows_the_rail_beside_it", RailwayGameTests::smallStraightAligns);
        bodies.put("track_takes_the_place_of_the_grass", RailwayGameTests::trackTakesTheGrassCell);
        bodies.put("stock_rides_a_vanilla_rail", RailwayGameTests::stockRidesVanillaRail);
        bodies.put(
                "an_unpowered_golden_rail_stops_stock",
                RailwayGameTests::unpoweredGoldenRailStopsStock);
        return bodies;
    }

    /**
     * Every track type in the table, laid into a real world, writes exactly the blocks it says.
     *
     * <p>One test rather than thirty-four: the per-type assertions are already unit tests against
     * the fixtures, and what is under test here is the applier, which is the same code for all of
     * them. A loop that stops at the first failure names the type it stopped on, which is all a
     * per-type test would have told anyone.
     */
    private static void everyTrackTypePlaces(GameTestHelper helper) {
        int checked = 0;
        for (TrackType type : TrackType.values()) {
            for (int facing = 0; facing < 4; facing++) {
                TrackPlan plan = TrackPlanCatalog.get(type, facing);
                if (plan == null) {
                    continue;
                }
                BlockPos origin = helper.absolutePos(new BlockPos(1, 2, 1));
                clear(helper, origin, plan);

                traincraft.track.PlacementResult result =
                        TrackPlacer.place(helper.getLevel(), origin, type, facing);
                if (!result.placed()) {
                    throw new AssertionError(
                            type + " facing " + facing + " refused to place: " + result.reason());
                }
                for (Placement placement : plan.placements()) {
                    BlockPos at = origin.offset(placement.dx(), placement.dy(), placement.dz());
                    var block = helper.getLevel().getBlockState(at).getBlock();
                    boolean rail =
                            block instanceof TrackBlock || block instanceof TrackOccupancyBlock;
                    if (!rail) {
                        throw new AssertionError(
                                type
                                        + " facing "
                                        + facing
                                        + " left "
                                        + at
                                        + " as "
                                        + block
                                        + " rather than track");
                    }
                }
                Placement first = plan.get(0);
                traincraft.track.TrackBreaker.dismantle(
                        helper.getLevel(),
                        origin.offset(first.dx(), first.dy(), first.dz()),
                        false);
                for (Placement placement : plan.placements()) {
                    BlockPos at = origin.offset(placement.dx(), placement.dy(), placement.dz());
                    if (!helper.getLevel().getBlockState(at).isAir()) {
                        throw new AssertionError(
                                type
                                        + " facing "
                                        + facing
                                        + " left a block after dismantling at "
                                        + at);
                    }
                }
                checked++;
            }
        }
        if (checked < 100) {
            throw new AssertionError(
                    "only "
                            + checked
                            + " type/facing pairs were placed;"
                            + " the table should hold hundreds");
        }
        helper.succeed();
    }

    private static void stockIsAlignedWhenPlaced(GameTestHelper helper) {
        BlockPos origin = helper.absolutePos(new BlockPos(5, 2, 5));
        Player player = helper.makeMockPlayer(net.minecraft.world.level.GameType.CREATIVE);
        var items = java.util.List.of(
                traincraft.bootstrap.ItemRegistry.LOCO_STEAM_ALICE.get(),
                traincraft.bootstrap.ItemRegistry.LOCO_STEAM_BR80.get(),
                traincraft.bootstrap.ItemRegistry.FREIGHT_CART_YELLOW.get());
        for (int facing = 0; facing < 4; facing++) {
            TrackPlan plan = TrackPlacementPlanner.plan(TrackType.VERY_LONG_STRAIGHT, facing);
            clear(helper, origin, plan);
            helper.assertTrue(
                    TrackPlacer.apply(helper.getLevel(), origin, plan).placed(),
                    "Placement failed");
            // Use a filler block well inside the piece, with rails on either side for the bogie.
            BlockPos clicked = plan.placements().stream()
                    .filter(p -> !p.gag())
                    .map(p -> origin.offset(p.dx(), p.dy(), p.dz()))
                    .findFirst().orElse(origin);
            int meta = TrackBlock.metaFromFacing(
                    helper.getLevel().getBlockState(clicked).getValue(TrackBlock.FACING));
            Placement middle = plan.placements().get(plan.size() / 2);
            clicked = origin.offset(middle.dx(), middle.dy(), middle.dz());
            for (var item : items) {
                int checked = 0;
                for (int direction = 0; direction < 8; direction++) {
                    player.setYRot(direction * 45.0F);
                    ItemStack stack = new ItemStack(item);
                    player.setItemInHand(net.minecraft.world.InteractionHand.MAIN_HAND, stack);
                    var hit = new net.minecraft.world.phys.BlockHitResult(
                            Vec3.atCenterOf(clicked), net.minecraft.core.Direction.UP, clicked, false);
                    item.useOn(new net.minecraft.world.item.context.UseOnContext(
                            player, net.minecraft.world.InteractionHand.MAIN_HAND, hit));
                    var placed = helper.getLevel().getEntitiesOfClass(
                            traincraft.vehicle.entity.RollingStockEntity.class,
                            new net.minecraft.world.phys.AABB(clicked).inflate(4));
                    // Existing placement rules can reject facing across the track.
                    for (var stock : placed) {
                        checked++;
                        float yaw = stock.getYRot();
                        float pitch = stock.getXRot();
                        String context = item + " facing=" + facing + " direction=" + direction;
                        double crossAxis = meta % 2 == 0
                                ? Math.sin(Math.toRadians(yaw)) : Math.cos(Math.toRadians(yaw));
                        helper.assertTrue(Math.abs(crossAxis) < 0.001,
                                "Incorrect spawn yaw: " + context + " yaw=" + yaw);
                        helper.assertTrue(
                                stock.tickCount == 0, "Assertion must precede first tick");
                        stock.tick();
                        helper.assertTrue(Math.abs(net.minecraft.util.Mth.wrapDegrees(stock.getYRot() - yaw)) < 0.01
                                        && Math.abs(stock.getXRot() - pitch) < 0.01,
                                "First tick changed orientation: " + context);
                        stock.discard();
                    }
                }
                helper.assertTrue(
                        checked > 0, "No placements checked for " + item + " facing=" + facing);
            }
        }
        helper.succeed();
    }

    private static void locomotiveAlignsWithTrack(GameTestHelper helper) {
        BlockPos origin = helper.absolutePos(new BlockPos(1, 2, 1));
        TrackPlan plan = TrackPlacementPlanner.plan(TrackType.VERY_LONG_STRAIGHT, 0);
        clear(helper, origin, plan);
        helper.assertTrue(
                TrackPlacer.apply(helper.getLevel(), origin, plan).placed(), "Placement failed");
        AliceLocomotiveEntity loco =
                helper.spawn(
                        EntityRegistry.LOCO_STEAM_ALICE.get(),
                        new Vec3(
                                1.5,
                                2.2 + traincraft.vehicle.entity.RollingStockEntity.Y_OFFSET,
                                3.5));
        loco.setYRot(90);
        helper.runAfterDelay(
                5,
                () -> {
                    helper.assertTrue(
                            Math.abs(Math.sin(Math.toRadians(loco.getYRot()))) < 0.001,
                            "Locomotive points across the rail: yaw=" + loco.getYRot());
                    loco.discard();
                    helper.succeed();
                });
    }

    /** Two carts set coupleable, close enough to each other, end up coupled both ways. */
    private static void coupleableStockCouples(GameTestHelper helper) {
        BlockPos origin = helper.absolutePos(new BlockPos(1, 2, 1));
        TrackPlan plan = TrackPlacementPlanner.plan(TrackType.VERY_LONG_STRAIGHT, 0);
        clear(helper, origin, plan);
        helper.assertTrue(
                TrackPlacer.apply(helper.getLevel(), origin, plan).placed(), "Placement failed");

        FreightCartYellowEntity first = freight(helper, 3.5);
        FreightCartYellowEntity second = freight(helper, 5.0);
        // Both have to have taken a coupling id first, which they do on their own first tick --
        // as they would have long before a player opened either screen.
        helper.runAfterDelay(
                5,
                () -> {
                    first.setArmed(true);
                    second.setArmed(true);
                });

        helper.runAfterDelay(
                15,
                () -> {
                    VehicleEnd firstEnd = first.endFacing(second);
                    VehicleEnd secondEnd = second.endFacing(first);
                    helper.assertTrue(first.hasLink(firstEnd), "The first cart did not couple");
                    helper.assertTrue(second.hasLink(secondEnd), "The second cart did not couple");
                    helper.assertTrue(
                            !first.isArmed() && !second.isArmed(),
                            "Coupling left the carts still hunting");
                    helper.assertTrue(
                            first.link(firstEnd) == second.getUniqueTrainID(),
                            "The first cart's link points at " + first.link(firstEnd));
                    helper.assertTrue(
                            second.link(secondEnd) == first.getUniqueTrainID(),
                            "The second cart's link points at " + second.link(secondEnd));
                    helper.assertTrue(
                            first.coupled(firstEnd) == second && second.coupled(secondEnd) == first,
                            "The carts do not hold each other");
                    first.discard();
                    second.discard();
                    helper.succeed();
                });
    }

    /** A coupling held longer than its optimal distance pulls both carts back towards it. */
    private static void aStretchedCouplingPulls(GameTestHelper helper) {
        BlockPos origin = helper.absolutePos(new BlockPos(1, 2, 1));
        TrackPlan plan = TrackPlacementPlanner.plan(TrackType.VERY_LONG_STRAIGHT, 0);
        clear(helper, origin, plan);
        helper.assertTrue(
                TrackPlacer.apply(helper.getLevel(), origin, plan).placed(), "Placement failed");

        FreightCartYellowEntity first = freight(helper, 3.5);
        FreightCartYellowEntity second = freight(helper, 9.5);
        couple(first, second);

        helper.runAfterDelay(
                10,
                () -> {
                    helper.assertTrue(
                            first.getDeltaMovement().z > 0.0,
                            "The leading cart was not pulled back: " + first.getDeltaMovement());
                    helper.assertTrue(
                            second.getDeltaMovement().z < 0.0,
                            "The trailing cart was not pulled up: " + second.getDeltaMovement());
                    first.discard();
                    second.discard();
                    helper.succeed();
                });
    }

    /**
     * A link whose other end is more than twenty blocks away is let go rather than dragged.
     *
     * <p>This is what upstream does with a cart whose chunk loaded somewhere else entirely.
     */
    private static void aLostLinkIsDropped(GameTestHelper helper) {
        FreightCartYellowEntity first = freight(helper, 1.5);
        FreightCartYellowEntity second = freight(helper, 25.5);
        couple(first, second);

        helper.runAfterDelay(
                10,
                () -> {
                    helper.assertTrue(!first.hasAnyLink(), "The link was kept: " + first.link1);
                    helper.assertTrue(first.cartLinked1 == null, "The cart was kept");
                    first.discard();
                    second.discard();
                    helper.succeed();
                });
    }

    /**
     * Two coupleable carts on neighbouring tracks stay apart.
     *
     * <p>They are within the reach the coupling measures -- it measures a horizontal distance --
     * and only the axis test tells them apart from two carts nose to tail on one track.
     */
    private static void parallelTrackDoesNotCouple(GameTestHelper helper) {
        FreightCartYellowEntity first = freight(helper, 3.5);
        FreightCartYellowEntity second =
                helper.spawn(
                        EntityRegistry.FREIGHT_CART_YELLOW.get(),
                        new Vec3(
                                2.5,
                                2.2 + traincraft.vehicle.entity.RollingStockEntity.Y_OFFSET,
                                3.5));
        first.setNewUniqueID(first.getId());
        second.setNewUniqueID(second.getId());
        first.updateTicks = 10;
        second.updateTicks = 10;
        first.setArmed(true);
        second.setArmed(true);

        new LinkHandler().tick(first);

        helper.assertTrue(!first.hasAnyLink(), "Coupled across to the next track");
        helper.assertTrue(!second.hasAnyLink(), "Coupled across to the next track");
        first.discard();
        second.discard();
        helper.succeed();
    }

    /** A pair already coupled at one end does not take a second coupling to each other. */
    private static void coupledStockDoesNotCoupleTwice(GameTestHelper helper) {
        FreightCartYellowEntity first = freight(helper, 3.5);
        FreightCartYellowEntity second = freight(helper, 5.0);
        couple(first, second);
        second.setPos(first.getX(), first.getY(), first.getZ() - 1.5);
        first.setArmed(true);
        second.setArmed(true);

        new LinkHandler().tick(first);

        helper.assertTrue(
                !first.hasLink(VehicleEnd.FRONT) || !first.hasLink(VehicleEnd.BACK),
                "The same pair coupled at both ends");
        first.discard();
        second.discard();
        helper.succeed();
    }

    /** Releasing the middle of three leaves three loose carts and no consist spanning them. */
    private static void decouplingAMiddleCarSplits(GameTestHelper helper) {
        FreightCartYellowEntity first = freight(helper, 2.0);
        FreightCartYellowEntity middle = freight(helper, 3.5);
        FreightCartYellowEntity last = freight(helper, 5.0);
        couple(first, middle);
        couple(middle, last);

        middle.unLink();

        helper.assertTrue(!middle.hasAnyLink(), "The middle cart kept a coupling");
        helper.assertTrue(!first.hasAnyLink(), "The leading cart kept a coupling");
        helper.assertTrue(!last.hasAnyLink(), "The trailing cart kept a coupling");
        helper.assertTrue(
                first.cartLinked1 == null && first.cartLinked2 == null,
                "The leading cart still holds the middle one");
        helper.assertTrue(
                last.cartLinked1 == null && last.cartLinked2 == null,
                "The trailing cart still holds the middle one");
        first.discard();
        middle.discard();
        last.discard();
        helper.succeed();
    }

    /** Cargo put into a freight cart is still there once it has run for a while. */
    private static void freightKeepsItsCargo(GameTestHelper helper) {
        FreightCartYellowEntity cart = freight(helper, 1.5);
        helper.assertTrue(
                cart.getContainerSize() == 36, "Wrong cargo size: " + cart.getContainerSize());
        cart.setItem(0, new ItemStack(Items.COAL, 17));
        helper.runAfterDelay(
                10,
                () -> {
                    helper.assertTrue(
                            cart.getItem(0).is(Items.COAL) && cart.getItem(0).getCount() == 17,
                            "The cargo did not survive: " + cart.getItem(0));
                    cart.discard();
                    helper.succeed();
                });
    }

    /** A cart pushed along six blocks of Minecraft rail travels, and stays on them. */
    private static void stockRidesVanillaRail(GameTestHelper helper) {
        BlockPos origin = helper.absolutePos(new BlockPos(1, 2, 1));
        for (int dz = 0; dz < 8; dz++) {
            helper.getLevel()
                    .setBlockAndUpdate(origin.offset(0, -1, dz), Blocks.STONE.defaultBlockState());
        }
        for (int dz = 0; dz < 8; dz++) {
            helper.getLevel().setBlock(origin.offset(0, 0, dz), Blocks.RAIL.defaultBlockState(), 3);
        }

        FreightCartYellowEntity cart = freight(helper, 1.5);
        double startZ = cart.getZ();
        cart.setDeltaMovement(0.0, 0.0, 0.2);

        helper.runAfterDelay(
                10,
                () -> {
                    helper.assertTrue(
                            cart.getZ() > startZ + 0.5,
                            "The cart did not run along the rail: " + cart.getZ());
                    helper.assertTrue(
                            Math.abs(cart.getX() - (origin.getX() + 0.5)) < 1.0E-6,
                            "The cart left the centreline: " + cart.getX());
                    cart.discard();
                    helper.succeed();
                });
    }

    /** Upstream's brake: an unpowered golden rail takes anything slower than 0.03 to a stop. */
    private static void unpoweredGoldenRailStopsStock(GameTestHelper helper) {
        BlockPos origin = helper.absolutePos(new BlockPos(1, 2, 1));
        for (int dz = 0; dz < 8; dz++) {
            helper.getLevel()
                    .setBlockAndUpdate(origin.offset(0, -1, dz), Blocks.STONE.defaultBlockState());
        }
        for (int dz = 0; dz < 8; dz++) {
            helper.getLevel()
                    .setBlock(origin.offset(0, 0, dz), Blocks.POWERED_RAIL.defaultBlockState(), 3);
        }

        FreightCartYellowEntity cart = freight(helper, 1.5);
        cart.setDeltaMovement(0.0, 0.0, 0.02);

        helper.runAfterDelay(
                10,
                () -> {
                    helper.assertTrue(
                            TrackMovement.planarSpeed(cart) == 0.0,
                            "The cart was not stopped: " + cart.getDeltaMovement());
                    cart.discard();
                    helper.succeed();
                });
    }

    private static FreightCartYellowEntity freight(GameTestHelper helper, double z) {
        return helper.spawn(
                EntityRegistry.FREIGHT_CART_YELLOW.get(),
                new Vec3(1.5, 2.2 + traincraft.vehicle.entity.RollingStockEntity.Y_OFFSET, z));
    }

    /** Couples two carts the way the buttons would, without needing a screen or a player. */
    private static void couple(
            traincraft.vehicle.entity.RollingStockEntity first,
            traincraft.vehicle.entity.RollingStockEntity second) {
        first.setNewUniqueID(first.getId());
        second.setNewUniqueID(second.getId());
        new LinkHandler()
                .couple(first, first.endFacing(second), second, second.endFacing(first));
        // The spring waits for both ends to have been ticking; a cart parked outside the test
        // area may never tick at all, so it is given the count it would have had.
        first.updateTicks = 10;
        second.updateTicks = 10;
    }

    /**
     * Nothing to stand on, nothing laid -- and not one block written before finding that out.
     *
     * <p>The hole is under a filler block rather than under the rail the player clicked, because
     * upstream checks every cell a piece occupies and a rule that only looked at the origin would
     * pass this test while still letting a curve hang off the edge of a cliff.
     */
    private static void trackRefusesToFloat(GameTestHelper helper) {
        BlockPos origin = helper.absolutePos(new BlockPos(1, 2, 1));
        TrackPlan plan = TrackPlacementPlanner.plan(TrackType.MEDIUM_TURN, 0);
        clear(helper, origin, plan);

        Placement filler =
                plan.placements().stream()
                        .filter(Placement::gag)
                        .findFirst()
                        .orElseThrow(() -> new AssertionError("a medium turn has filler blocks"));
        BlockPos hole = origin.offset(filler.dx(), filler.dy(), filler.dz()).below();
        helper.getLevel().setBlockAndUpdate(hole, Blocks.AIR.defaultBlockState());

        traincraft.track.PlacementResult result =
                TrackPlacer.place(helper.getLevel(), origin, TrackType.MEDIUM_TURN, 0);
        helper.assertTrue(
                result instanceof traincraft.track.PlacementResult.NoSupport,
                "A piece with one unsupported filler was not refused: " + result);
        for (Placement placement : plan.placements()) {
            BlockPos pos = origin.offset(placement.dx(), placement.dy(), placement.dz());
            helper.assertTrue(
                    helper.getLevel().getBlockState(pos).isAir(),
                    "The refused placement still wrote " + pos);
        }
        helper.succeed();
    }

    /** Knock the ground out from under one block and the whole piece comes down, item and all. */
    private static void trackDiesWithItsSupport(GameTestHelper helper) {
        BlockPos origin = helper.absolutePos(new BlockPos(1, 2, 1));
        TrackPlan plan = TrackPlacementPlanner.plan(TrackType.MEDIUM_TURN, 0);
        clear(helper, origin, plan);
        helper.assertTrue(
                TrackPlacer.apply(helper.getLevel(), origin, plan).placed(), "Placement failed");

        Placement middle = plan.placements().get(plan.size() / 2);
        BlockPos under = origin.offset(middle.dx(), middle.dy(), middle.dz()).below();
        helper.getLevel().setBlockAndUpdate(under, Blocks.AIR.defaultBlockState());

        helper.runAfterDelay(
                2,
                () -> {
                    for (Placement placement : plan.placements()) {
                        BlockPos pos =
                                origin.offset(placement.dx(), placement.dy(), placement.dz());
                        var block = helper.getLevel().getBlockState(pos).getBlock();
                        helper.assertTrue(
                                !(block instanceof TrackBlock
                                        || block instanceof TrackOccupancyBlock),
                                "Track left standing at " + pos + " after its support went");
                    }
                    // Upstream returns the item: destroyBlock(..., false) suppresses only its own
                    // drop, and breakBlock still hands back idDrop.
                    long dropped =
                            helper.getLevel()
                                    .getEntitiesOfClass(
                                            net.minecraft.world.entity.item.ItemEntity.class,
                                            net.minecraft.world.phys.AABB.ofSize(
                                                    net.minecraft.world.phys.Vec3.atCenterOf(origin),
                                                    32.0,
                                                    32.0,
                                                    32.0))
                                    .stream()
                                    .filter(
                                            item ->
                                                    item.getItem().getItem()
                                                            == traincraft.bootstrap.TrackItemRegistry
                                                                    .itemFor(TrackType.MEDIUM_TURN))
                                    .count();
                    helper.assertTrue(
                            dropped == 1,
                            "Expected one track item back, found " + dropped);
                    helper.succeed();
                });
    }

    /**
     * Clicking the top of a rail with a track item lays nothing.
     *
     * <p>This is the report that started the rule: the port aimed the new piece at the block above
     * whatever face was clicked, so a click on the top of a rail put a second piece a block up in
     * the air. Driven through the item's own {@code useOn}, because the two halves of the fix meet
     * there -- where the piece is aimed, and whether the ground under it will hold it.
     */
    private static void aRailIsNotGroundForARail(GameTestHelper helper) {
        BlockPos relative = new BlockPos(1, 2, 1);
        BlockPos origin = helper.absolutePos(relative);
        TrackPlan plan = TrackPlacementPlanner.plan(TrackType.SMALL_STRAIGHT, 0);
        clear(helper, origin, plan);
        helper.assertTrue(
                TrackPlacer.apply(helper.getLevel(), origin, plan).placed(), "Placement failed");

        Player player = helper.makeMockPlayer(net.minecraft.world.level.GameType.CREATIVE);
        player.setItemInHand(
                net.minecraft.world.InteractionHand.MAIN_HAND,
                new ItemStack(
                        traincraft.bootstrap.TrackItemRegistry.itemFor(TrackType.SMALL_STRAIGHT)));
        helper.useBlock(
                relative,
                player,
                new net.minecraft.world.phys.BlockHitResult(
                        net.minecraft.world.phys.Vec3.atCenterOf(origin.above()),
                        net.minecraft.core.Direction.UP,
                        origin,
                        false));

        helper.assertTrue(
                helper.getLevel().getBlockState(origin.above()).isAir(),
                "A click on the top of a rail laid track in the air");
        helper.succeed();
    }

    /**
     * Track laid on tall grass goes where the grass was, not on top of it.
     *
     * <p>Upstream's {@code getPlacementHeight} decrements Y for a replaceable block, which is the
     * other half of ignoring the clicked face. Aiming above the grass instead puts the piece one
     * block too high -- and, now that the ground rule exists, refuses it outright.
     */
    private static void trackTakesTheGrassCell(GameTestHelper helper) {
        BlockPos relative = new BlockPos(1, 2, 1);
        BlockPos origin = helper.absolutePos(relative);
        TrackPlan plan = TrackPlacementPlanner.plan(TrackType.SMALL_STRAIGHT, 0);
        clear(helper, origin, plan);
        for (Placement placement : plan.placements()) {
            helper.getLevel()
                    .setBlockAndUpdate(
                            origin.offset(placement.dx(), placement.dy(), placement.dz()),
                            Blocks.SHORT_GRASS.defaultBlockState());
        }

        Player player = helper.makeMockPlayer(net.minecraft.world.level.GameType.CREATIVE);
        player.setItemInHand(
                net.minecraft.world.InteractionHand.MAIN_HAND,
                new ItemStack(
                        traincraft.bootstrap.TrackItemRegistry.itemFor(TrackType.SMALL_STRAIGHT)));
        helper.useBlock(
                relative,
                player,
                new net.minecraft.world.phys.BlockHitResult(
                        net.minecraft.world.phys.Vec3.atCenterOf(origin),
                        net.minecraft.core.Direction.UP,
                        origin,
                        false));

        helper.assertTrue(
                helper.getLevel().getBlockState(origin).getBlock() instanceof TrackBlock,
                "Track was not laid in the grass's own cell: "
                        + helper.getLevel().getBlockState(origin));
        helper.assertTrue(
                helper.getLevel().getBlockState(origin.above()).isAir(),
                "Something was laid above the grass as well");
        helper.succeed();
    }

    private static void smallStraightAligns(GameTestHelper helper) {
        BlockPos origin = helper.absolutePos(new BlockPos(1, 2, 1));
        TrackPlan plan = TrackPlacementPlanner.plan(TrackType.SMALL_STRAIGHT, 0);
        clear(helper, origin, plan);
        clear(helper, origin.south(), plan);
        helper.assertTrue(
                TrackPlacer.apply(helper.getLevel(), origin, plan).placed(), "Placement failed");

        Player player = helper.makeMockPlayer(net.minecraft.world.level.GameType.CREATIVE);
        player.setYRot(90.0F);
        player.setItemInHand(
                net.minecraft.world.InteractionHand.MAIN_HAND,
                new ItemStack(
                        traincraft.bootstrap.TrackItemRegistry.itemFor(TrackType.SMALL_STRAIGHT)));
        helper.useBlock(
                new BlockPos(1, 2, 2),
                player,
                new net.minecraft.world.phys.BlockHitResult(
                        net.minecraft.world.phys.Vec3.atCenterOf(origin.south()),
                        net.minecraft.core.Direction.UP,
                        origin.south(),
                        false));

        helper.assertTrue(
                helper.getLevel().getBlockEntity(origin.south()) instanceof TrackBlockEntity rail
                        && traincraft.track.TrackFacing.toDirection(rail.getFacing()).getAxis()
                                == net.minecraft.core.Direction.Axis.Z,
                "A small straight beside a rail along Z was laid across it");
        helper.succeed();
    }

    private static void preservesAdjacentPiece(GameTestHelper helper) {
        BlockPos origin = helper.absolutePos(new BlockPos(1, 2, 1));
        TrackPlan plan = TrackPlacementPlanner.plan(TrackType.SMALL_STRAIGHT, 0);
        BlockPos adjacent = origin.east();
        clear(helper, origin, plan);
        clear(helper, adjacent, plan);
        helper.assertTrue(
                TrackPlacer.apply(helper.getLevel(), origin, plan).placed(),
                "First placement failed");
        helper.assertTrue(
                TrackPlacer.apply(helper.getLevel(), adjacent, plan).placed(),
                "Adjacent placement failed");
        helper.getLevel().destroyBlock(origin, false);
        helper.assertTrue(
                helper.getLevel().getBlockEntity(adjacent) instanceof TrackBlockEntity,
                "Removing one assembly destroyed its neighbour");
        clear(helper, adjacent, plan);
        helper.succeed();
    }

    private static void blockedPlacementChangesNothing(GameTestHelper helper) {
        BlockPos origin = helper.absolutePos(new BlockPos(1, 2, 1));
        TrackPlan plan = TrackPlacementPlanner.plan(TrackType.MEDIUM_TURN, 0);
        clear(helper, origin, plan);
        Placement last = plan.get(plan.size() - 1);
        BlockPos blocked = origin.offset(last.dx(), last.dy(), last.dz());
        helper.getLevel().setBlock(blocked, Blocks.STONE.defaultBlockState(), Block.UPDATE_ALL);
        helper.assertTrue(
                TrackPlacer.apply(helper.getLevel(), origin, plan)
                        instanceof traincraft.track.PlacementResult.Blocked,
                "A blocked plan must be rejected");
        for (Placement placement : plan.placements()) {
            BlockPos pos = origin.offset(placement.dx(), placement.dy(), placement.dz());
            helper.assertTrue(
                    pos.equals(blocked)
                            ? helper.getLevel().getBlockState(pos).is(Blocks.STONE)
                            : helper.getLevel().getBlockState(pos).isAir(),
                    "Rejected placement changed " + pos);
        }
        clear(helper, origin, plan);
        helper.succeed();
    }

    private static void breakingTakesThePiece(GameTestHelper helper) {
        BlockPos origin = helper.absolutePos(new BlockPos(1, 2, 1));
        TrackPlan plan = TrackPlanCatalog.get(TrackType.MEDIUM_TURN, 0);
        if (plan == null) {
            throw new AssertionError("no plan for MEDIUM_TURN facing 0");
        }
        clear(helper, origin, plan);
        TrackPlacer.place(helper.getLevel(), origin, TrackType.MEDIUM_TURN, 0);

        // A block in the middle, not the one that was clicked: the interesting case is a filler
        // block, which has to find the piece it belongs to before it can take it with it.
        Placement middle = plan.placements().get(plan.size() / 2);
        BlockPos at = origin.offset(middle.dx(), middle.dy(), middle.dz());
        helper.getLevel().destroyBlock(at, false);

        for (Placement placement : plan.placements()) {
            BlockPos each = origin.offset(placement.dx(), placement.dy(), placement.dz());
            var block = helper.getLevel().getBlockState(each).getBlock();
            if (block instanceof TrackBlock || block instanceof TrackOccupancyBlock) {
                throw new AssertionError("breaking " + at + " left " + each + " standing");
            }
        }
        helper.succeed();
    }

    /**
     * A thrown switch rewrites the rail ahead of it into the matching turn, and releasing it puts a
     * straight back. This is the routing itself: without the rewrite a train curves for the one
     * block of pointwork and is put straight again by the next rail.
     */
    private static void thrownSwitchRewritesTheRoute(GameTestHelper helper) {
        BlockPos origin = helper.absolutePos(new BlockPos(1, 2, 1));
        TrackPlan plan = TrackPlanCatalog.get(TrackType.MEDIUM_SWITCH, 0);
        if (plan == null) {
            throw new AssertionError("no plan for MEDIUM_SWITCH facing 0");
        }
        clear(helper, origin, plan);
        TrackPlacer.place(helper.getLevel(), origin, TrackType.MEDIUM_SWITCH, 0);

        BlockPos switchAt = origin.offset(0, 0, 1);
        BlockPos ahead = origin.offset(0, 0, 2);
        if (!(helper.getLevel().getBlockEntity(switchAt) instanceof TrackBlockEntity pointwork)) {
            throw new AssertionError("no rail tile at the pointwork " + switchAt);
        }
        if (!(helper.getLevel().getBlockEntity(ahead) instanceof TrackBlockEntity route)) {
            throw new AssertionError("no rail tile ahead of the switch at " + ahead);
        }
        if (route.getTrackType() != TrackType.SMALL_STRAIGHT) {
            throw new AssertionError(
                    "the rail ahead starts as "
                            + route.getTrackType()
                            + " rather than SMALL_STRAIGHT");
        }

        pointwork.setSwitchActive(true);
        if (route.getTrackType() != TrackType.MEDIUM_LEFT_TURN) {
            throw new AssertionError(
                    "a thrown switch left the rail ahead as " + route.getTrackType());
        }
        pointwork.setSwitchActive(false);
        if (route.getTrackType() != TrackType.SMALL_STRAIGHT) {
            throw new AssertionError(
                    "a released switch left the rail ahead as " + route.getTrackType());
        }
        helper.succeed();
    }

    /**
     * Upstream's {@code shouldIgnoreSwitch}: wheels coming back along the straight leg push thrown
     * points over instead of being flung onto the branch arc.
     */
    private static void trailingThroughThrownSwitch(GameTestHelper helper) {
        BlockPos origin = helper.absolutePos(new BlockPos(1, 2, 1));
        TrackPlan plan = TrackPlanCatalog.get(TrackType.MEDIUM_SWITCH, 0);
        clear(helper, origin, plan);
        TrackPlacer.place(helper.getLevel(), origin, TrackType.MEDIUM_SWITCH, 0);
        TrackBlockEntity pointwork =
                (TrackBlockEntity) helper.getLevel().getBlockEntity(origin.offset(0, 0, 1));
        pointwork.setSwitchActive(true);

        FreightCartYellowEntity cart = freight(helper, 4.9);
        cart.setYRot(180);
        cart.alignToTrackOnPlacement();
        cart.setDeltaMovement(0, 0, -0.15);
        for (int tick = 0; tick < 25; tick++) {
            // An unpowered cart coasts down; keep it rolling as a locomotive behind it would.
            cart.setDeltaMovement(0, 0, -0.15);
            cart.tick();
            helper.assertTrue(
                    Math.abs(cart.getX() - origin.getX() - 0.5) < 0.05,
                    "Thrown onto the branch at tick " + tick + ": x=" + (cart.getX() - origin.getX()));
        }
        helper.assertTrue(
                cart.getZ() < origin.getZ() + 1.0,
                "Did not run through the switch: z=" + (cart.getZ() - origin.getZ()));
        helper.assertTrue(!pointwork.isSwitchActive(), "Trailing wheels did not reset the switch");
        helper.assertTrue(pointwork.isManualOverride(), "The reset is not held against redstone");
        cart.discard();
        helper.succeed();
    }

    private static void chme3CrossesParallelSwitch(GameTestHelper helper) {
        BlockPos origin = helper.absolutePos(new BlockPos(8, 4, 20));
        for (var segment : java.util.List.of(
                Map.entry(origin.offset(0, 0, -12), TrackType.VERY_LONG_STRAIGHT),
                Map.entry(origin, TrackType.MEDIUM_PARALLEL_SWITCH),
                Map.entry(origin.offset(3, 0, 11), TrackType.VERY_LONG_STRAIGHT))) {
            TrackPlan plan = TrackPlacementPlanner.plan(segment.getValue(), 0);
            clear(helper, segment.getKey(), plan);
            // The long approach crosses the test template's barrier wall.
            for (Placement placement : plan.placements()) {
                BlockPos rail = segment.getKey().offset(placement.dx(), placement.dy(), placement.dz());
                for (int height = 1; height <= 4; height++) {
                    helper.getLevel().setBlockAndUpdate(rail.above(height), Blocks.AIR.defaultBlockState());
                }
            }
            helper.assertTrue(TrackPlacer.apply(helper.getLevel(), segment.getKey(), plan).placed(),
                    "Could not place switch approach");
        }
        ((TrackBlockEntity) helper.getLevel().getBlockEntity(origin.offset(0, 0, 1)))
                .setSwitchActive(true);
        for (int direction : new int[] {1, -1}) {
            var loco = EntityRegistry.LOCO_DIESEL_CHME3.get().create(
                    helper.getLevel(), net.minecraft.world.entity.EntitySpawnReason.COMMAND);
            loco.setPos(origin.getX() + (direction > 0 ? 0.5 : 3.5),
                    origin.getY() + 0.85, origin.getZ() + (direction > 0 ? -4.0 : 15.0));
            loco.setYRot(direction > 0 ? 0 : 180);
            loco.alignToTrackOnPlacement();
            loco.restoreFuel(5000);
            loco.setTemperature(loco.getAverageOverheat());
            loco.setEngineOn(true);
            loco.setDeltaMovement(0, 0, direction * 0.075);
            var wagon = EntityRegistry.FREIGHT_CART_YELLOW.get().create(
                    helper.getLevel(), net.minecraft.world.entity.EntitySpawnReason.COMMAND);
            wagon.setPos(loco.getX(), loco.getY(), loco.getZ() - direction * 2.97);
            wagon.setYRot(loco.getYRot());
            wagon.alignToTrackOnPlacement();
            wagon.setDeltaMovement(loco.getDeltaMovement());
            couple(loco, wagon);
            for (int tick = 0; tick < 310; tick++) {
                // Supply steady traction while retaining the direction selected by the track.
                loco.setDeltaMovement(loco.getDeltaMovement().normalize().scale(0.075));
                loco.tick();
                wagon.tick();
                helper.assertTrue(loco.cartLinked1 == wagon && wagon.cartLinked1 == loco,
                        "Coupling broke on the switch at tick " + tick
                                + " direction=" + direction
                                + " loco=" + loco.position().subtract(Vec3.atLowerCornerOf(origin))
                                + " wagon=" + wagon.position().subtract(Vec3.atLowerCornerOf(origin)));
                helper.assertTrue(Math.abs(wagon.getY() - origin.getY() - 0.85) < 0.05,
                        "Wagon left the switch at tick " + tick);
                var bogie = loco.bogiePosition();
                double wheelbase = Math.hypot(bogie.x - loco.getX(), bogie.z - loco.getZ());
                helper.assertTrue(wheelbase > 0.6 && wheelbase < 1.8,
                        "Bogie left its locomotive at tick " + tick + ": " + wheelbase);
                helper.assertTrue(Math.abs(loco.getY() - origin.getY() - 0.85) < 0.05,
                        "Locomotive left the switch at tick " + tick);
            }
            helper.assertTrue(direction > 0 ? loco.getZ() > origin.getZ() + 11
                            : loco.getZ() < origin.getZ(),
                    "Locomotive did not cross the switch in direction " + direction
                            + " position=" + loco.position().subtract(Vec3.atLowerCornerOf(origin))
                            + " speed=" + loco.getDeltaMovement() + " engine=" + loco.isEngineOn());
            helper.assertTrue(direction > 0 ? wagon.getZ() > origin.getZ() + 11
                            : wagon.getZ() < origin.getZ(),
                    "Wagon did not follow the locomotive through the switch");
            loco.discard();
            wagon.discard();
        }
        helper.succeed();
    }

    /**
     * A locomotive on a straight takes coal out of its fuel slot and spends it.
     *
     * <p>Everything here is server-side and none of it is reachable from a unit test: the entity
     * has to exist in a level, tick, and find the rail under itself.
     */
    private static void locomotiveBurnsFuel(GameTestHelper helper) {
        BlockPos origin = helper.absolutePos(new BlockPos(1, 2, 1));
        TrackPlan plan = TrackPlanCatalog.get(TrackType.VERY_LONG_STRAIGHT, 0);
        if (plan != null) {
            clear(helper, origin, plan);
        }
        TrackPlacer.place(helper.getLevel(), origin, TrackType.VERY_LONG_STRAIGHT, 0);

        // The framework's own spawn path rather than create + addFreshEntity: it takes
        // test-relative coordinates, adds the entity through the level the test owns and registers
        // it for cleanup. Placing one by hand left it at the world border with a tick count of
        // zero -- never added, never ticked, and the failure said only that the firebox was empty.
        AliceLocomotiveEntity loco =
                helper.spawn(
                        EntityRegistry.LOCO_STEAM_ALICE.get(),
                        new Vec3(
                                1.5,
                                2.0 + traincraft.vehicle.entity.RollingStockEntity.Y_OFFSET,
                                3.5));
        loco.setItem(LocomotiveEntity.FUEL_SLOT, new ItemStack(Items.COAL, 8));
        if (loco instanceof SteamLocomotiveEntity steam) {
            steam.fillWater(1000);
        }
        loco.setTemperature(loco.getAverageOverheat());

        // assertTrue, not a bare AssertionError: succeedWhen retries its asserter every tick and
        // only GameTestAssertException means "not yet". An AssertionError escapes the sequence and
        // takes the server down on the first evaluation, which is why this used to report a tick
        // count of zero however the entity was spawned.
        helper.succeedWhen(
                () -> {
                    helper.assertTrue(
                            loco.getFuel() > 0,
                            "the firebox never took the coal: slot="
                                    + loco.getItem(LocomotiveEntity.FUEL_SLOT)
                                    + " engine="
                                    + loco.isEngineOn()
                                    + " age="
                                    + loco.tickCount
                                    + " pos="
                                    + loco.position());
                    helper.assertTrue(
                            loco.getItem(LocomotiveEntity.FUEL_SLOT).getCount() < 8,
                            "the fuel slot still holds all eight");
                });
    }

    /**
     * A cold boiler holds the locomotive still, and a lit one heats until it does not.
     *
     * <p>This is the one behaviour of the boiler that a driver meets immediately: a locomotive
     * fresh off the item is cold and will not move however hard it is driven, and stays that way
     * for a few hundred ticks. Getting it wrong in either direction is invisible in a screenshot
     * and obvious in play, so it is checked here rather than by eye.
     *
     * <p>The velocity is set along Z because a very long straight laid facing 0 runs that way, and
     * the track discards whatever is laid across it.
     */
    private static void coldLocomotiveWillNotMove(GameTestHelper helper) {
        BlockPos origin = helper.absolutePos(new BlockPos(1, 2, 1));
        TrackPlan plan = TrackPlanCatalog.get(TrackType.VERY_LONG_STRAIGHT, 0);
        if (plan != null) {
            clear(helper, origin, plan);
        }
        TrackPlacer.place(helper.getLevel(), origin, TrackType.VERY_LONG_STRAIGHT, 0);

        AliceLocomotiveEntity loco =
                helper.spawn(
                        EntityRegistry.LOCO_STEAM_ALICE.get(),
                        new Vec3(
                                1.5,
                                2.0 + traincraft.vehicle.entity.RollingStockEntity.Y_OFFSET,
                                3.5));
        loco.setItem(LocomotiveEntity.FUEL_SLOT, new ItemStack(Items.COAL, 8));
        if (loco instanceof SteamLocomotiveEntity steam) {
            steam.fillWater(1000);
        }
        // Deliberately not seeded: the point is the state it starts in.
        loco.setTemperature(0);

        helper.startSequence()
                // The fire is lit and the level climbs. One in seven ticks, so this is a handful
                // of ticks' wait, not a hundred.
                .thenWaitUntil(
                        () ->
                                helper.assertTrue(
                                        loco.getOverheatLevel() > 5,
                                        "the boiler is not heating: level="
                                                + loco.getOverheatLevel()
                                                + " fuel="
                                                + loco.getFuel()
                                                + " engine="
                                                + loco.isEngineOn()))
                .thenExecute(() -> loco.setDeltaMovement(0.0, 0.0, 0.1))
                .thenExecuteAfter(
                        2,
                        () -> {
                            helper.assertTrue(
                                    loco.getState() == HeatState.COLD,
                                    "expected a cold boiler, found "
                                            + loco.getState().displayName()
                                            + " at level "
                                            + loco.getOverheatLevel());
                            helper.assertTrue(
                                    TrackMovement.planarSpeed(loco) == 0.0,
                                    "a cold locomotive moved at "
                                            + TrackMovement.planarSpeed(loco));
                        })
                .thenExecute(() -> loco.setTemperature(loco.getAverageOverheat()))
                .thenExecuteAfter(
                        2,
                        () ->
                                helper.assertTrue(
                                        loco.getState() == HeatState.HOT,
                                        "a boiler at its average should be hot, found "
                                                + loco.getState().displayName()))
                .thenExecute(() -> loco.setDeltaMovement(0.0, 0.0, 0.1))
                .thenExecuteAfter(
                        3,
                        () ->
                                helper.assertTrue(
                                        TrackMovement.planarSpeed(loco) > 0.01,
                                        "a hot locomotive was held still at "
                                                + TrackMovement.planarSpeed(loco)))
                .thenSucceed();
    }

    /** Wipes the volume a plan is about to fill, so one test cannot inherit another's blocks. */
    /**
     * Empties a plan's footprint and lays solid ground under it.
     *
     * <p>The ground is not decoration: track has to rest on a solid top surface, so a test
     * structure of nothing but air is a place no piece can be laid. Upstream needs the same
     * continuous ground under a piece, slopes included.
     */
    private static void clear(GameTestHelper helper, BlockPos origin, TrackPlan plan) {
        for (Placement placement : plan.placements()) {
            BlockPos pos = origin.offset(placement.dx(), placement.dy(), placement.dz());
            helper.getLevel().setBlockAndUpdate(pos, Blocks.AIR.defaultBlockState());
            helper.getLevel().setBlockAndUpdate(pos.below(), Blocks.STONE.defaultBlockState());
        }
    }

    /** Referenced so the block registry is loaded before the first test asks about a rail. */
    @SuppressWarnings("unused")
    private static final Object BLOCKS = BlockRegistry.class;
}
