[build]
  base = "landing"
  command = "yarn generate"
  publish = ".output/public"

[build.environment]
  NODE_VERSION = "22"

[[headers]]
  for = "/_nuxt/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
